const Sentry = require('$sentry');
const db = require('$db');
const service_email = require("$services/Mail/index");
const JWT = require('jsonwebtoken')
const yup = require('yup')

/**
 * @generator controller generated by kraaken-cli
 * @param req
 * @param res
 * @description NotificationController
 * @type {Express}
 */
const CreateNotificationController = async (req, res) => {

    try {
        const { uuid } = req.params;
        const { message } = req.body

        const schema = yup.object().shape({
            message: yup.string().required(),
            uuid: yup.string().uuid().required()
        })

        if (! await schema.validate({message: message, uuid: uuid})){
            return res.status(400).json({
                message: 'Bad Request',
                errors: schema.errors
            })
        }

        const user = await db.user.findUnique({
            where: {
                uuid
            },
        });

        if (user){
            try {
                await db.notifications.create({
                    data: {
                        message: message,
                        isRead: false,
                        user: {
                            connect:{
                                uuid: uuid
                            }
                        }
                    }
                });
            } catch (err){
               
               
                return res.status(500).json({
                    error: "",
                    message: "Can't create notification"
                })
            }

            const userNotification = await db.user.findUnique({
                where: {
                    uuid,
                },
                include: {
                    notifications: true
                }
            });

            return res.status(200).json([...userNotification.notifications])
        }

        return res.status(500).json({
            error: "",
            message: "User not found"
        })
    } catch (err){
        /**
         * @type {Kraaken|prisma}
         * @description Send error to kraaken
         */
       

        /**
         * @description returning an error from request
         */
        return res.status(500).send({
            error: err.message
        })
    }

}

/**
 * @description Exporting only function, because they will be auto discovered.
 * @type {function}
 */
module.exports = CreateNotificationController