const Controller = require("$controllers");

module.exports = [
  /**
   * @generator route generated by kraaken-cli
   * @Route : /action/reset-password/key
   * @Method : post
   * @param {string} key le lien actionKey
   * @param {string} password le nouveau mot de passe
   */
  {
    url: "/action/user/reset-password/:key",
    method: "post",
    func: [Controller["ActionController@ressetPassword"]],
  },
  /**
   * permet d'envoyer un email permettant a l'utilisateur de renitialiser son mot de passe
   * @Route : /action/reset-password
   * @Method : post
   * @param {string} email || phone
   */
  {
    url: "/action/user/reset-password",
    method: "post",
    func: [Controller["ActionController@forgotPassword"]],
  },
  /**
   *route permettant de signaler une usurpation et de desactiver un compte afin que l'utilisateur puisse redefinir un nouveau mot de passe
   * @Route : /action/reset-password
   * @Method : post
   * @param {string} email || phone
   */
  {
    url: "/action/user/usurpation/:key",
    method: "post",
    func: [Controller["ActionController@usurpation"]],
  },
];
