const Controller = require('$controllers');

module.exports = [
    /**
     * @generator route generated by kraaken-cli
     * @Route : /url
     * @Method : get
     */
    {
        url: "/avatar",
        method: "post",
        func: [Controller['AvatarController@index']],
        functionName: 'index',
        perm: ['*']
    },

    /**
     * @generator route generated by kraaken-cli
     * @Route : /url
     * @Method : post
     * @protected
     */
    {
        url: "/avatar/:uuid/:name",
        method: "get",
        func: [Controller['AvatarController@get']],
        functionName: 'get',
    },
];
