const Controller = require('$controllers');

module.exports = [
    /**
     * @generator route generated by kraaken-cli
     * @Route : /notifications/:uuid
     * @Method : get
     * @protected
     */
    {
        url: "/notifications/:uuid",
        method: "get",
        func: [Controller['NotificationController@index']],
        functionName: 'index',
    },

    /**
     * @generator route generated by kraaken-cli
     * @Route : /notifications/create/:uuid
     * @Method : post
     * @protected
     */
    {
        url: "/notifications/create/:uuid",
        method: "post",
        func: [Controller['NotificationController@create']],
        functionName: 'create',
        perm: ['*']
    },

    /**
     * @generator route generated by kraaken-cli
     * @Route : /notifications/read/:uuid
     * @Method : post
     * @protected
     */
    {
        url: "/notifications/read/:uuid",
        method: "post",
        func: [Controller['NotificationController@read']],
        functionName: 'read',
        perm: ['*']
    },

    /**
     * @generator route generated by kraaken-cli
     * @Route : /notifications/delete/:uuid
     * @Method : post
     * @protected
     */
    {
        url: "/notifications/delete/:uuid",
        method: "post",
        func: [Controller['NotificationController@delete']],
        functionName: 'delete',
        perm: ['*']
    },
];
