const Sentry = require('$sentry');
const db = require('$db');
const service_email = require("$services/Mail/index");
const Validator = require("$class/Validator");
const JWT = require('jsonwebtoken')
const Kraaken = require('$class/Kraaken');

/**
 * @generator controller generated by kraaken-cli
 * @param req
 * @param res
 * @description __CONTROLLER__
 * @type {Express}
 */
const __CONTROLLER__ = async (req, res) => {

    try {
        // TODO: Let's do some magic thing's here !

        return res.status(200).send()
    } catch (err){
        /**
         * @type {Kraaken|prisma}
         * @description Send error to kraaken
         */
        const kraaken = new Kraaken()
        await kraaken.captureError(err);

        /**
         * @description returning an error from request
         */
        return res.status(500).send('Server Error');
    }

}

/**
 * @description Exporting only function, because they will be auto discovered.
 * @type {function}
 */
module.exports = __CONTROLLER__