const Controller = require('$controllers');

module.exports = [
    /**
     * @generator route generated by kraaken-cli
     * @Route : /url
     * @Method : get
     */
    {
        url: "/url",
        method: "get",
        func: [Controller['ControllerName@MethodName']],
        functionName: 'functionName'
    },

    /**
     * @generator route generated by kraaken-cli
     * @Route : /url
     * @Method : post
     * @protected
     */
    {
        url: "/url",
        method: "post",
        func: [Controller['ControllerName@MethodName']],
        functionName: 'functionName',
        perm: ['ROLE_USER']
    },
];
